server:
  port: 8080
  host: localhost

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: aura
  sslmode: disable
  max_conns: 10
  timeout: 5s
  read_only: false
